---
title: Dylan Edwards
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
repository: jilliangmeehan/dylan-edwards
